config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :locations
    resources :stops
  end

  root 'users#index'

  post 'finduser' => 'stops#find_user', as: :find_user

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user
end

app/models/stop.rb
class Stop < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :roll_num, presence: true
	validates :bus_num, presence: true
	before_save :to_lowercase
	has_many :locations, dependent: :destroy
	has_many :stops, dependent: :destroy


	def to_lowercase
		self.roll_num.downcase!
		self.bus_num.downcase!
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	skip_before_filter :verify_authenticity_token

	def index

	end
	
	def new
		@user = User.find(params[:user_id])
	end

	def create
		@user = User.find(params[:user_id])

		@location = @user.locations.build(location_params)

		if @location.save
			render json: @user.locations.count
		else
			#render :json => {'error': 'cannot save location into database'}
			render nothing: true
		end
	end

	private
	def location_params
		params.require(:location).permit(:lat, :long)
	end
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
	skip_before_filter :verify_authenticity_token


	def index
		@user = User.find(params[:user_id])

		@stops = @user.stops.all
	end

	def new
		@user = User.new
	end

	def find_user
		if @user = User.where(['roll_num = ? and bus_num = ?', user_params[:roll_num], user_params[:bus_num]])
			redirect_to user_stops_path(@user.first)
		else
			render 'new'
		end
	end

	def update
		@user = User.find(params[:user_id])

		if @user.stops.update(params[:id], stop_params)
			render json: @user.locations.count
		else
			render :nothing
		end
	end

	private
	def stop_params
		params.require(:stop).permit(:stop_name, :lat, :long)
	end

	def user_params
		params.require(:user).permit(:roll_num, :bus_num)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index

	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to new_user_location_path(@user)
		else
			render 'new'
		end
	end

	def show

	end

	private

	def user_params
		params.require(:user).permit(:roll_num, :bus_num)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!! 5

%html
%head
	%title Datagather2
	%meta{:content => 'width=device-width, initial-scale=1.0', :name => 'viewport'}
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body
	= yield


/  <!DOCTYPE html>
/ <html>
/ <head>
/   <title>Datagather2</title>
/   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
/   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
/   <%= csrf_meta_tags %>
/ </head>
/ <body>

/ <%= yield %>

/ </body>
/ </html>

app/views/locations/index.html.haml
%h1 Locations Index page

app/views/locations/new.html.haml
.container
	.row
		.col-xs-12
			%button.btn.btn-primary.btn-lg.btn-block.start{onclick: 'getLocationUpdate()', :data =>{:id => @user.id}} Start 
			%button.btn.btn-primary.btn-lg.btn-block.stop{onclick: 'stopWatch()'} stop
	.row
		.col-xs-12
			%div.alert.alert-success 
				%h3
					<span class='times'>0</span> records have been added

app/views/stops/index.html.haml
%h1 All Stops

%ul
	- @stops.each do |stop|
		%li{id: "#{stop.id}", class: 'btn btn-default btn-primary btn-block get-loc', onclick: 'getSingleLoc(this.id)', :data =>{:uid => @user.id, :sid => stop.id}} "#{stop.stop_name}"

app/views/stops/new.html.haml
.container
	.row
		.col-xs-12
			- if @user.errors.any?
				#errors
					%p= pluralize(@user.errors.count, ' errors prevented this user from saving')

					%ul
						- @user.errors.full_messages.each do |error|
							%li= error
	.row
		.col-xs-12
			= form_for :user, url: find_user_path do |f|
				= f.label :roll_num
				= f.text_field :roll_num, class: 'form-control', placeholder: 'k11-2132'

				= f.label :bus_num
				= f.text_field :bus_num, class: 'form-control', placeholder: '15'

				= f.submit class: 'btn btn-primary btn-lg'

app/views/users/index.html.haml
.container
	.row.automatic
		.col-sm-12
			= link_to 'Automatic', new_user_path, class: 'btn btn-primary btn-lg btn-block'
	.row.manual
		.col-sm-12
			= link_to 'Manual', new_user_stop_path(2), class: 'btn btn-primary btn-lg btn-block'
	/ .row
	/ 	.col-sm-12
	/ 		= link_to 'Automatic', new_user_path, class: 'btn btn-primary btn-lg btn-block'

app/views/users/new.html.haml
.container
	.row
		.col-xs-12
			- if @user.errors.any?
				#errors
					%p= pluralize(@user.errors.count, ' errors prevented this user from saving')

					%ul
						- @user.errors.full_messages.each do |error|
							%li= error
	.row
		.col-xs-12
			= form_for @user do |f|
				= f.label :roll_num
				= f.text_field :roll_num, class: 'form-control', placeholder: 'k11-2132'

				= f.label :bus_num
				= f.text_field :bus_num, class: 'form-control', placeholder: '15'

				= f.submit class: 'btn btn-primary btn-lg'